js/CharModel.js, js/Controller.js, test/charmodel_energy.html, test/controller_char_test.html
As far as functionality with energy is concerned, this is done. The controller will need to be worked on once the mapModel is ready so we can start to piece the logic together.
=> Character energy

tools/loadMap.py
Add clearing local storage code in loadMap.py
Signed-off-by: Mi Yon Kim <miyon@pdx.edu>
=> Clearing localstorage before loading map

GameViewTest.html, style.css
Check it out! Got the layout going.
=> General ui

initWebpage.html, styles.css
Buttons integrated with controller and character model.
=> Init webpage

.gitignore, js/Tile.js, js/mapModel.js, test/Map_object.html, test/Tile_object.html
Updated the Tile object with constants
mapModel is complete as far as I can tell, but it handles all the basic functionality.  We can add exception handling in if we see fit.
Updated my tests for the changes and it passes.
=> Hero movement

js/Controller.js, js/MapView.js, test/mapview_test.html
It's really ugly, but it is working by first creating all cells needed
in the table, then updating only the cells in the mapModel since it
is sparsley populated.
=> MapView Initial Work

js/Controller.js, js/MessageModel.js, js/MessageView.js, test/mapview_test.html
Now we can write a single message to the screen.
=> MessageView and Model

js/MapView.js, test/mapview_test.html
Mapview supports all terrains in Tile.js now.
=> Mapview now handles multiple terrains

js/CharModel.js
Whiffles is the named used in FRUPAL Project Packet 1.pdf, so it's
canonical now.
=> Renamed the frupal currency to whiffles

js/Controller.js, js/MapView.js, js/mapModel.js, test/map_setVisible_test.html, test/mapview_test.html
There is still a bug where wrapping takes two turns, but on the second turn you do end up having moved two spaces, but this has mapview_test.html with cells moving and lighting up.
=> Map model controller david

js/CharModel.js, js/Controller.js, js/mapModel.js, test/RoyalDiamonds1_test.html, test/mapview_test.html
I feel good about this code, but please pay attention to my changes in mapModel.js. I made small changes to fix issues in the movement code. I just branched from master, and there they were. But I know the mapModel branch also fixes those issues and will be moved soon. So, tell me if I'm doing anything wrong by changing them here.
The requirements for this feature are pretty weird. For example, Warren's map file doesn't contain any diamonds! I talk about this in comments.
It does work as specified, as you can see in a debugger running the test
html file.
I think we'll need to revisit this a few times, like if/when we add
support for items, because the diamonds may end up being a kind of item.
=> Added the "royal diamonds" win condition feature

js/Controller.js, js/MapView.js
Character is now updated in MapView.
=> Add Character Indicater to MapView

js/CharStatusView.js, js/Controller.js, test/mapview_test.html
This is a basic implementation that displays character status (energy,
money, location) to text fields on the web page. I integrated it with
the mapview_test.html file. The front end html files are not in master
yet to integrate with, but it will be easy to do that once they arrive.
=> Added CharStatusView class

maps/raw/default.map
Location to store raw maps that have not been processed by
loadMap.py. The idea is to store the raw maps here, then use
loadMap.py and place the html into maps.
=> Add Raw Maps to maps directory

js/Controller.js
I tested this using mapview_test.html. This code mirrors the code that
loads the game state which was in mapview_test.html's loadMap function
(as of this writing).
Sorry for any confusion with my initial saveToLocalStorage branch. I somehow got Aiden's gameView.html added in that branch, so I deleted it to prevent confusing diffs.
=> Implemented saving the game state to localStorage

maps/raw/both.map, maps/raw/noDiamond.map, maps/raw/outsideCell.map, tools/loadMap.py
Add check logic in loadMap.py
Add map files (noDiamond, containsOutsideCells, both)
Signed-off-by: Mi Yon Kim <youn0125@gmail.com>
=> Change loadMap.py to check corrupted contents from file

js/Controller.js
The fix looks good and works, should merge this before the demo.
=> Displays tile message

js/mapModel.js
I moved the wrapping code into a single function named wrap. This
removes a lot of repetitions of the wrapping code. This fixes a few
small bugs in wrapping code, but mostly it makes the code smaller. It
also prepares us to add binoculars and sight range later on.
=> Refactored MapModel to consolidate code that wraps edges of map

js/Controller.js, js/mapModel.js, maps/enconter_power_bar_test_map.html
I've tested this for Wei Cao and looked over the code, everything looks good and I recommend merge.
=> Enconter power bar

js/CharModel.js, js/Controller.js, js/FrupalModel.js, js/mapModel.js, maps/Sample_Frugal.html
Added the binoculars to the game.  Also made changes to the charModel to have a visRange.  This variable is used in the mapModel to reveal the correct amount of tiles around the character.  Once the binoculars are found the visRange variable is changed to 2 in the charModel.  I have tested this in chrome and it seems to work.  Please feel free to check it out.
=> Binoculars

js/Controller.js, maps/Labrynth.html, maps/raw/Labrynth.map
This implements the Type 1 and Type 2 treasure chest user stories. I
added treasure chests to the left side of the Labrynth map so you can
test them.
=> Added Treasure Chests

js/Controller.js, maps/default.map.html, maps/raw/tilesObstacles.map, maps/tilesObstacles.html
I've finished 3 user stories for Sprint 2:
Encounter Water (River/Lake),
Encounter a Bog,
Encounter an Obstacle
=> Encounter tiles and obstacles

gameView.html, js/Controller.js, js/FrupalModel.js, maps/Labrynth.map.html, maps/both.map.html, maps/cellTooHigh.map.html, maps/cellTooLow.map.html, maps/default.map.html, maps/noDiamond.map.html, maps/tilesObstacles.map.html, tools/loadMap.py
This fixes #58  that Gennadii talked about in class today. The message model wasn't saving + loading. This looked bad when the player loses/wins the game because the message (the only explanation of why the game is over) could disappear.
This updates the Labrynth and Sample Frugal maps, which are the main ones we test on, I think.
=> Added saving/loading the MessageModel along with rest of the model

gameView.html, style.css
- Renamed "Messages to Read" to just "Messages".
- Removed bacon ipsum text
- Fixed the boxes after removing bacon ipsum so that they grey all lines up.  Looks cleaner now.
=> Remove bacon ipsum
